name = "safonov"
author = "gabik"
version = "5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "515a32a8553d3d6e0029ddbb124d2db0a8eb9b1a56d14db7cd52e17ebee2df94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
