name = "safonov"
author = "gabik"
version = "5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f884d9d417d0e4b1ce0756b94b2d1a66519320fef807a4800214a7f8234b1685"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
